### 登录
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "username": "TTTest1",
  "password": "123456"
}


### 登录
POST http://47.93.166.101:10511/api/user/login
Content-Type: application/json

{
  "username": "TTTest1",
  "password": "123456"
}

###
GET http://47.93.166.101:10511/user/userinfo
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJUVFRlc3QxIiwiaWF0IjoxNzM4NzY4NTM5LCJleHAiOjE3Mzg4NTQ5Mzl9.VHdbapoFA3pmlhFkMbVfTX8q6--waYyMK35Bs4UxPvA


### 更新用户密码
PATCH http://47.93.166.101:10511/user/updatePwd
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJUVFRlc3QxIiwiaWF0IjoxNzM4NzY4NTM5LCJleHAiOjE3Mzg4NTQ5Mzl9.VHdbapoFA3pmlhFkMbVfTX8q6--waYyMK35Bs4UxPvA
Content-Type: application/json

{
  "old_pwd":"1234567",
  "new_pwd":"123456",
  "re_pwd":"123456"
}