spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: big_event
    password: Stavage
    url: jdbc:mysql://localhost:3306/big_event
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    sql: debug
    org:
      example: debug
      springframework:
        data:
          jdbc: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

my:
  secretkey: Stavage

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启Java驼峰命名和数据库下划线命名的转换(直接输入camel自动提示)

